### PR TITLE
UKRs managed by server for Connect apps

### PR DESCRIPTION
**Pull request by OrangeAndGreen**
Changed code so when logging into a Connect app for the first time, a random DB passphrase is no longer generated locally. Instead, the standard HQ login call is made (using token auth instead of password), and the returned server-managed DB passphrase is used for encrypting the app database.

Note that a random local password is still generated to encrypt the DB passphrase so it can be stored in the unencrypted global database.

### CODE REVIEW

**Review by pm-dimagi — APPROVED** [review]

**Comment by OrangeAndGreen** [comment]
@damagatchi retest this please

**Comment by OrangeAndGreen** [comment]
@damagatchi retest this please

**Comment by OrangeAndGreen** [comment]
@damagatchi retest this please

**Comment by OrangeAndGreen** [comment]
@damagatchi retest this please

**Pull request merged**
