### PR TITLE
Adds "XPathEncryptStringFunc" to fix  testAllExternalizablesInPrototypeFactory

### PR DESCRIPTION
**Pull request by shubham1g5**

### CODE REVIEW

**Review by ctsims — APPROVED** [review]

**Review by ShivamPokhriyal — APPROVED** [review]

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi  retest this please

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462128/)

**Pull request merged**
