### PR TITLE
Copy CCC Global database changes - Version 6

### PR DESCRIPTION
**Pull request by avazirna**
## Summary
This PR is to copy Global DB changes that were done as part of the CCC work. The goal with bringing these changes is to ensure a healthy update from that version to production. Changes included here are:
- Addition of table to global DB for storing ConnectKeyRecords (changed DB version to 6)

## Safety Assurance
- [X] I have confidence that this PR will not introduce a regression for the reasons below

### Safety story
I believe this is safe as we are only adding a new table to the Global DB that is used by CCC. 

cross-request: https://github.com/dimagi/commcare-core/pull/1416

### CODE REVIEW

**Comment by avazirna** [comment]
@damagatchi retest this please

**Review by shubham1g5 — COMMENTED** [review]
Code Looks ok to me and will let @OrangeAndGreen confirm if it merges all DB changes from Connect. 

Also we will need to test the update from current Playstore version to 2.54 after merging this.

**Review by OrangeAndGreen — COMMENTED** [review]
I think we'll need to include the upgrade to V7 as well, which adds a column to the table for ConnectKeyRecord. Users on the latest beta already have this additional change.

**Comment by avazirna** [comment]
> I think we'll need to include the upgrade to V7 as well, which adds a column to the table for ConnectKeyRecord. Users on the latest beta already have this additional change.

Yes, I'm going to raise a separate PR for V7.

**Comment by avazirna** [comment]
@damagatchi retest this

**Comment by avazirna** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@shubham1g5 just an update to the externalizable classes list, can I have your approval again?

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
