### PR TITLE
Operate on hintText view only when it's non null

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
StackTrace: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.commcare.views.ShrinkingTextView.setVisibility(int)' on a null object reference
    at org.commcare.views.widgets.QuestionWidget.hideHintText(QuestionWidget.java:678)
    at org.commcare.views.QuestionsView.<init>(QuestionsView.java:133)
    at org.commcare.activities.FormEntryActivityUIController.createView(FormEntryActivityUIController.java:353)
    at org.commcare.activities.FormEntryActivityUIController.showNextView(FormEntryActivityUIController.java:444)
    at org.commcare.activities.FormEntryActivityUIController.showNextView(FormEntryActivityUIController.java:387)
    at org.commcare.activities.FormEntryActivityUIController.lambda$setupUI$0$FormEntryActivityUIController(FormEntryActivityUIController.java:112)
    at org.commcare.activities.-$$Lambda$FormEntryActivityUIController$dnpmuqxhXm7dnwgMxFbWNnARv1g.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7184)
    at android.view.View.performClickInternal(View.java:7161)
    at android.view.View.access$3500(View.java:818)
    at android.view.View$PerformClick.run(View.java:27683)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7562)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
Fixes a bug where an empty hint texts inside a question list will cause commcare to crash.

### CODE REVIEW

**Comment by shubham1g5** [comment]
@ShivamPokhriyal  can you add the stacktrace for the crash.

**Comment by ShivamPokhriyal** [comment]
> @ShivamPokhriyal can you add the stacktrace for the crash.

Sorry about not adding it earlier. I've updated the description with the stack trace.

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Review by shubham1g5 — APPROVED** [review]

**Comment by shubham1g5** [comment]
You probably need to merge master to fix the breaking test.

**Comment by ShivamPokhriyal** [comment]
> You probably need to merge master to fix the breaking test.

Gotcha Thanks!

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462213/)

**Pull request merged**
