### PR TITLE
Backmerge Commcare 2.50.2

### PR DESCRIPTION
**Pull request by shubham1g5**
Contains: https://github.com/dimagi/commcare-android/pulls?q=is%3Apr+milestone%3A2.50.2

### CODE REVIEW

**Review by ShivamPokhriyal — DISMISSED** [review]
One concern: We need to update `commcare_version` in strings.xml as well.

**Comment by shubham1g5** [comment]
yeah this is not ready/finalized yet, just created this a bit early to track changes for 2.50.2

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462016/)

**Comment by shubham1g5** [comment]
Closing this since all the PR's are merged individually into master.

**Pull request closed without merging**
