### PR TITLE
Use array length instead of hard code

### PR DESCRIPTION
**Pull request by wpride**
Fixes http://manage.dimagi.com/default.asp?240363

cc @proteusvacuum

### CODE REVIEW

**Comment by proteusvacuum** [comment]
Woo! (are there no tests for this?)

**Comment by wpride** [comment]
I doubt it, think this is still pretty much in hack-world

**Comment by phillipm** [comment]
lol

**Comment by ctsims** [comment]
It should be quite trivial to generate robolectric tests for this, fwiw

**Comment by ctsims** [comment]
@wspride Are we going to add any tests around this? The change looks good, but agree that test coveage would be very good.

**Comment by wpride** [comment]
@ctsims @phillipm pushed a test that triggers this exception on master - however, the test still passes because the crash happens on a not-main thread. Have either of you run into this before?

**Pull request merged**
