### PR TITLE
Add jacoco code coverage plugin

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**

### CODE REVIEW

**Comment by ShivamPokhriyal** [comment]
[0% (0.0%) vs master 0%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/461811/)

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by ShivamPokhriyal** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/461812/)

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@ShivamPokhriyal  we should expedite this as it's going to break checks on other PRs.

**Review by shubham1g5 — APPROVED** [review]

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Pull request merged**
