### PR TITLE
Revert "gradle.properties changes for build speed"

### PR DESCRIPTION
**Pull request by amstone326**
Reverts dimagi/commcare-android#1932

### CODE REVIEW

**Comment by shubham1g5** [comment]
Why revert 😢

**Comment by amstone326** [comment]
@shubham1g5 It was causing the build on jenkins to fail so I need to figure out why

**Comment by shubham1g5** [comment]
It might have been because of some gradle cache.. since the PR builder job was building successfully I think. Deleting the workspace and rebuilding might resolve the issue.

**Comment by amstone326** [comment]
Good thought, I'll give that a shot

**Pull request merged**
