### PR TITLE
[SAAS-12107] Handle captive portal in app installs

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
Jira https://dimagi-dev.atlassian.net/browse/SAAS-12107

Detect captive portals during app installs and provide a better error message to the user.

cross-request: https://github.com/dimagi/commcare-core/pull/994

### CODE REVIEW

**Comment by dimagimon** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462398/)

**Review by shubham1g5 — APPROVED** [review]

**Comment by dimagimon** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462411/)

**Comment by shubham1g5** [comment]
@ShivamPokhriyal Are you missing a commit, I don't see the change of `CaptivePortalRedirectException` to `IOException` ?

**Comment by ShivamPokhriyal** [comment]
> @ShivamPokhriyal Are you missing a commit, I don't see the change of `CaptivePortalRedirectException` to `IOException` ?

That's in the core submodule https://github.com/dimagi/commcare-core/pull/994/files#diff-caf78695fa86cf4a8d5d6ed16fc350505713faf23812df52254cd2ca57a30384R12.

**Review by shubham1g5 — APPROVED** [review]
Looks good. Thank you for iterating with the `IOException` !

**Pull request merged**
