### PR TITLE
Media Capture encryption

### PR DESCRIPTION
**Pull request by shubham1g5**
## Summary

- Stores the media capture files encrypted and decrypt the file for viewing if required

## Product Description

- Encrypts any recorded media files through audio, video, image and signature capture questions

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

There doesn't seem to be any test covergae in this area and we only rely on Manual QA for testing of media capture widgets. Looking for feedback on what particular areas should we be testing here.

### CODE REVIEW

**Comment by dimagimon** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR does not contain any JIRA issue keys in the PR title or commit messages (e.g. KEY-123)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ctsims — APPROVED** [review]
This looks great to me. 

The only thing that I wasn't quite sure about was the handling of edge cases around partial files. Since we're doing a lot of file manipulation, I think it's going to be increasingly likely that we'll have some broken files where we create a file for the decrypted version of an image or audio, start writing, and then something goes wrong. 

I think the clearest cases where that might happen would involve being logged out, or otherwise be big app level events, in which case the eventual restart of the app would clear the temp folders, so probably not something to spend a ton of time worrying about, but I wanted to mention in case anything jumped to mind around handling those edge cases.

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by ctsims — APPROVED** [review]
The new test looks great, glad we could get that codified for regressions.

Looking it over, this PR makes a ton of great contributions in restructure even outside of the core changes. Thanks for the detail work on this one

**Pull request merged**
