### PR TITLE
Lts backport installer update

### PR DESCRIPTION
**Pull request by ctsims**
Backports https://github.com/dimagi/commcare-android/pull/1309 From 2.28 to CommCare LTS on 2.27

cross-request: https://github.com/dimagi/commcare-core/pull/532

### CODE REVIEW

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
confirmed that these are clean. They may not be _right_, but we can't test them against the modern PR builders. Integrating into 2.27 for potential LTS point release

**Comment by phillipm** [comment]
:metal:

**Comment by ctsims** [comment]
Sup, @phillipm. Do you know whether I was right about https://github.com/dimagi/commcare-android/pull/1660 being floating (No PR)?

**Comment by phillipm** [comment]
Hey! Are you referring to the commit referenced in https://github.com/dimagi/commcare-core/pull/534? If so, I'm pretty sure I pushed it directly to master to fix a build issue, because https://github.com/dimagi/commcare-core/commit/7366ad6054783cca26f77761d2e5fdea4e237b0f came 2 minutes after the merge of https://github.com/dimagi/commcare-core/pull/311

**Comment by ctsims** [comment]
#tight.

That's what it looked like. Thanks, Bro! I hope your days are sunny and
full of fun code!

**Pull request merged**
