### PR TITLE
Split non-DB centric sorting into commcare-core utility

### PR DESCRIPTION
**Pull request by wpride**
Splits out the non-database layer portions of the entity sorting code into the `EntitySorterUtil` class in `commare-core` for usage in Formplayer.

cross-request: https://github.com/dimagi/commcare-core/pull/764

### CODE REVIEW

**Comment by wpride** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@wpride this build now keeps failing, I'm not sure why

**Comment by wpride** [comment]
@amstone326 Either intermittent or merging `master` resolved

**Pull request merged**
