### PR TITLE
Changes to support Core Api Changes for Formplayer

### PR DESCRIPTION
**Pull request by shubham1g5**
cross-request: https://github.com/dimagi/commcare-core/pull/984

### CODE REVIEW

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by ctsims — APPROVED** [review]

**Comment by ShivamPokhriyal** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR does not contain any JIRA issue keys in the PR title or commit messages (e.g. KEY-123)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/dfbfa78a1f7ce192311bd0733fcbe27c84b04c79/app/src/org/commcare/activities/QueryRequestActivity.java#L110">app/src/org/commcare/activities/QueryRequestActivity.java#L110</a> - Using 'Log' instead of 'Timber'</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/dfbfa78a1f7ce192311bd0733fcbe27c84b04c79/app/src/org/commcare/activities/QueryRequestActivity.java#L349">app/src/org/commcare/activities/QueryRequestActivity.java#L349</a> - Using 'Log' instead of 'Timber'</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/dfbfa78a1f7ce192311bd0733fcbe27c84b04c79/app/src/org/commcare/activities/QueryRequestActivity.java#L449">app/src/org/commcare/activities/QueryRequestActivity.java#L449</a> - Using 'Log' instead of 'Timber'</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by dimagimon** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462347/)

**Pull request merged**
