### PR TITLE
Show Finish button on advancing to end of form

### PR DESCRIPTION
**Pull request by shubham1g5**
Refreshes view to show Finish button on advancing to end of form instead of triggering auto-save. 

Jira: https://dimagi-dev.atlassian.net/browse/MOB-41

Product Note: If there is a required date widget on the last screen in the form, earlier swiping ahead would auto-save the form. We have now changed this behaviour to instead show Finish button on swiping ahead and user needs to click on the Finish button to trigger save on the form.

### CODE REVIEW

**Comment by shubham1g5** [comment]
@ctsims If you think we should look into preserving Auto-Save for Auto-Advance setups, can you please set up a quick form displaying Auto-Advance functionality.

**Comment by ctsims** [comment]
Hi Shubham!

I made a form that should have demonstrated this behavior here:
https://www.commcarehq.org/a/swat/apps/view/4f507cb183d1562ad59513fc79a8ddd7/releases/

but on my device it looks like it already does what you outlined (Finish button pops up and you have to click it), so I think this is a safe change in behavior.

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@ctsims Thanks! Didn't realize it's just the `quick` appearance attribute.  I was thinking that it's more a form level setting which gets applied to every question in the form.

**Pull request merged**
