### PR TITLE
Formplayer to Master update

### PR DESCRIPTION
**Pull request by shubham1g5**
## Summary

Changes for https://github.com/dimagi/commcare-core/pull/1120

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Safety story

- Tested for apk update and seems to work fine. We are able to retain incomplete forms as well. So there doesn't seem to be any breaking serialization changes in regards to apk update
- Relying on Test coverage and QA to check for any regressions

Should be merged only once https://github.com/dimagi/commcare-android/pull/2584 is merged in this branch

Best reviewed commit by commit. 

cross-request: https://github.com/dimagi/commcare-core/pull/1120

### CODE REVIEW

**Comment by damagatchi** [comment]
Can one of the admins verify this patch?

**Review by snopoke — DISMISSED** [review]

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by snopoke — APPROVED** [review]

**Pull request merged**
