### PR TITLE
Update zxing

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
Jira https://dimagi-dev.atlassian.net/browse/SAAS-11557

Updates zxing library to 4.2.0 https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions

### CODE REVIEW

**Review by shubham1g5 — DISMISSED** [review]
Confirming that this has been tested on your end ?

**Comment by ShivamPokhriyal** [comment]
> Confirming that this has been tested on your end ?

I scanned a couple barcodes and it worked fine. I'm not sure if any other areas need to be tested with this change.

**Comment by ShivamPokhriyal** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/build.gradle#L0">app/build.gradle#L0</a> - <code>httpclient</code> defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for <code>httpclient</code> use <code>HttpUrlConnection</code> or <code>okhttp</code> instead), or repackaging the library using something like <code>jarjar</code>.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/build.gradle#L50">app/build.gradle#L50</a> - <code>json</code> defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for <code>httpclient</code> use <code>HttpUrlConnection</code> or <code>okhttp</code> instead), or repackaging the library using something like <code>jarjar</code>.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          8 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L5">app/AndroidManifest.xml#L5</a> - This <code>versionCode</code> value (<code>106</code>) is not used; it is always overridden by the value specified in the Gradle build script (<code>1</code>)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L13">app/AndroidManifest.xml#L13</a> - This namespace declaration is redundant</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L16">app/AndroidManifest.xml#L16</a> - This namespace declaration is redundant</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L19">app/AndroidManifest.xml#L19</a> - This namespace declaration is redundant</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L81">app/AndroidManifest.xml#L81</a> - Attribute <code>usesCleartextTraffic</code> is only used in API level 23 and higher (current min is 16)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L357">app/AndroidManifest.xml#L357</a> - Exported receiver does not require permission</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L364">app/AndroidManifest.xml#L364</a> - Exported receiver does not require permission</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/52425744747d2433e22b20495a02080325ae0c40/app/AndroidManifest.xml#L371">app/AndroidManifest.xml#L371</a> - Exported receiver does not require permission</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:link: <a href="https://dimagi-dev.atlassian.net/browse/SAAS-11557">SAAS-11557</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dimagimon** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462351/)

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
