### PR TITLE
Show PromptAPK activity for version mismatch error

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-10748

Using this change, for version mismatch errors, we'll now launch PromptAPKUpdateActivity. 

Product Note: For Version Mismatch errors, CommCare will now launch a new screen with details about the required version and buttons to launch PlayStore to update the app.

### CODE REVIEW

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please.

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@ShivamPokhriyal  Some late feedback. Wodndering in case an in-app update is available, will user also get shown the in app update dialogue on top of the prompt ? If so, the update prompt should not be forced in this case since user might not be in a proper network area and an immediate update will block him for long without allowing him to work on the older app version.

**Comment by ShivamPokhriyal** [comment]
Yeah it makes sense if they're installing app locally. Will make the
changes.

**Comment by ShivamPokhriyal** [comment]
> @ShivamPokhriyal Some late feedback. Wodndering in case an in-app update is available, will user also get shown the in app update dialogue on top of the prompt ? If so, the update prompt should not be forced in this case since user might not be in a proper network area and an immediate update will block him for long without allowing him to work on the older app version.

On second thought, users can always kill the app and then get back to what they wanna do after opening it again, so I think forced update will work.

**Comment by shubham1g5** [comment]
I still think it's better that we don't rely on user killing the app as a mechanism to get out of a certain workflow.

**Pull request merged**
