### PR TITLE
Shifts Kujaku to download from maven central

### PR DESCRIPTION
**Pull request by shubham1g5**
https://github.com/dimagi/commcare-android/issues/2473

### CODE REVIEW

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by ctsims — APPROVED** [review]

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by dimagimon** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/c9d428bc7da448ebdc303c2d50827d1706ed4655/app/build.gradle#L0">app/build.gradle#L0</a> - <code>httpclient</code> defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for <code>httpclient</code> use <code>HttpUrlConnection</code> or <code>okhttp</code> instead), or repackaging the library using something like <code>jarjar</code>.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><a href="https://github.com/dimagi/commcare-android/blob/c9d428bc7da448ebdc303c2d50827d1706ed4655/app/build.gradle#L49">app/build.gradle#L49</a> - <code>json</code> defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for <code>httpclient</code> use <code>HttpUrlConnection</code> or <code>okhttp</code> instead), or repackaging the library using something like <code>jarjar</code>.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR does not contain any JIRA issue keys in the PR title or commit messages (e.g. KEY-123)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damagatchi** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462426/)

**Pull request merged**
