### PR TITLE
Use RelativeLayout instead of ConstraintLayout for mediaview

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
This PR reverts #2355 and uses a RelativeLayout instead of ConstraintLayout.

### CODE REVIEW

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Review by shubham1g5 — APPROVED** [review]
nice turn around on it. Looks good to me mostly though will rely more on integrations tests and soem manual testing on it to confirm various use cases of this works correctly.

**Comment by ShivamPokhriyal** [comment]
Weird I'm seeing: `There is signature mismatch between application APK and test-suite APK. Package org.commcare.dalvik.test does not have a signature matching the target package org.commcare.dalvik. Please fix this, upload your app & test-suite APK and execute the test again.`

**Comment by ShivamPokhriyal** [comment]
> Weird I'm seeing: `There is signature mismatch between application APK and test-suite APK. Package org.commcare.dalvik.test does not have a signature matching the target package org.commcare.dalvik. Please fix this, upload your app & test-suite APK and execute the test again.`

@shubham1g5 Wondering if you have any thoughts on this one?

**Comment by shubham1g5** [comment]
@ShivamPokhriyal Are you able to repro locally ? My guess would be that test apk is not getting signed with the release keystore that you should be able to confirm by downloading the apk from Jenkins

**Comment by ShivamPokhriyal** [comment]
@shubham1g5 I think the issue is with the app bundles. I used an apk and it ran successfully. So I'm gonna merge this one and figure out the app bundle issue later.

**Pull request merged**
