### PR TITLE
[SAAS-12118] Use different user for different test

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-12118

We see intermittent failures during login while running our instrumentation tests. [Here](https://sentry.io/organizations/dimagi/issues/1825000918/?environment=production&project=136860&query=is%3Aunresolved+domain%3Aui-tests&statsPeriod=14d) is the sentry error log. 
The issue is happening because we're trying to login same user in multiple device at the same time, which is not supported by HQ.  Since we're running our tests in 5 shards parallelly, there is always a possibility where the same user sends a login request from different shard at the same time. 

The fix here is to use different user for every tests.

### CODE REVIEW

**Comment by ShivamPokhriyal** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:link: <a href="https://dimagi-dev.atlassian.net/browse/SAAS-12118">SAAS-12118</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ShivamPokhriyal** [comment]
Added dummy data for tests 
@damagatchi retest this please.

**Review by shubham1g5 — APPROVED** [review]
Great catch on this!

**Comment by ShivamPokhriyal** [comment]
Fixed data in tile test
@damagatchi retest this please

**Comment by dimagimon** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462409/)

**Pull request merged**
