### PR TITLE
Added new translation

### PR DESCRIPTION
**Pull request by stephherbers**
Added new translation for the title of "Case Claim." 
Just confirming there no syntax/other things I need to be aware of.
Relates to this [PR](https://github.com/dimagi/commcare-core/pull/958)

### CODE REVIEW

**Comment by orangejenny** [comment]
Added @ShivamPokhriyal since @shubham1g5 is out and I'm not positive where this translation belongs.

**Review by ShivamPokhriyal — APPROVED** [review]
👍🏻

**Comment by ShivamPokhriyal** [comment]
I see that https://github.com/dimagi/commcare-core/pull/958 PR was merged into the `formplayer` branch and not `master`. I guess we'll have to make another PR there for `master` or maybe we can merge `formplayer` changes into `master` before the next release.

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462183/)

**Pull request merged**
