### PR TITLE
Make properties of type String so values from HQ are compatible

### PR DESCRIPTION
**Pull request by amstone326**

### CODE REVIEW

**Comment by wpride** [comment]
One question: do we need to worry about migrations at all? IE if someone has saved a Preference as an `int`, updates, then the code tries to pull it with `Preferences.getString` will that fail?

**Comment by amstone326** [comment]
@wpride Oops, sorry about that. 

As for your question, the existence of these properties has not been released yet; they were only first added in a PR targeting 2.43: https://github.com/dimagi/commcare-android/pull/1945. It's also not possible for users to specify custom properties in HQ as integers; they are automatically sent as strings, which is why I needed to make this change.

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@damagatchi retest this please

**Pull request merged**
