### PR TITLE
Update gradle wrapper

### PR DESCRIPTION
**Pull request by wpride**
Update gradle wrapper (IE running `gradle wrapper`), remove files from `.gitignore`

### CODE REVIEW

**Comment by amstone326** [comment]
@wpride Hey would you mind explaining a little more what the goal of this is? The diff is intimidating haha. (Also, is this ready to go otherwise?)

**Comment by amstone326** [comment]
Oh hm that was weird, it was showing that the build had passed when I first opened this (I thought) but now it says checks have failed. From the failure message, it looks like it may just be due to being out of sync with master though. Not positive

**Comment by wpride** [comment]
@damagatchi retest this please

**Comment by wpride** [comment]
@amstone326 The entire diff is generated by rebuilding the gradle wrapper (IE running `gradle wrapper`) - this updates the executable to use the most recent code

**Pull request merged**
