### PR TITLE
Fixes case db migration

### PR DESCRIPTION
**Pull request by shubham1g5**
## Summary
https://dimagi-dev.atlassian.net/browse/QA-3228

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

None

### Safety story

Mostly relying on QA update tests due to which we were able to find out this issue during QA itself.

### CODE REVIEW

**Review by ShivamPokhriyal — APPROVED** [review]

**Comment by dimagimon** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR does not contain any JIRA issue keys in the PR title or commit messages (e.g. KEY-123)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by shubham1g5** [comment]
@ShivamPokhriyal  the same [BS error](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462521/console) again, were you able to add the debug log for it ?

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by ShivamPokhriyal** [comment]
> @ShivamPokhriyal the same [BS error](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462521/console) again, were you able to add the debug log for it ?

Ahh again! Lemme find that commit and raise a PR.

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by damagatchi** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462527/)

**Pull request merged**
