### PR TITLE
Bug fix: default values are not visibile for free text case prompts

### PR DESCRIPTION
**Pull request by shubham1g5**
1. Before this default values were not getting shown for text intput case prompts on mobile. 
2. Default values for the unsupported prompts were getting passed to search query which was breaking the search. 

cross-request: https://github.com/dimagi/commcare-core/pull/982

### CODE REVIEW

**Comment by dimagimon** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462314/)

**Review by ShivamPokhriyal — APPROVED** [review]

**Review by ctsims — APPROVED** [review]
Is the `isPromptSupported` method already present in `commcare-core` and the android implementation was redundant, or does this need a cross-request?

**Comment by shubham1g5** [comment]
> Is the isPromptSupported method already present in commcare-core and the android implementation was redundant, or does this need a cross-request?

Sorry I didn't realize rest of my changes are in core. Updated the PR with cross request.

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by ctsims — APPROVED** [review]

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@ShivamPokhriyal just an fyi that I am getting a [dummy failure](https://app-automate.browserstack.com/dashboard/v2/builds/848a66a24e605d20b356451c3ecb6fb20d00b7ae) on the integration tests when there are no tests left to be run in the end. 

Merging without test pass since it seems to be the issue with integration test setup.

**Pull request merged**
