### PR TITLE
Cache "smart" image inflation outputs to disk to prevent needing to perform the interpolation over and over.

### PR DESCRIPTION
**Pull request by ctsims**
Created a cache for images which are inflated to match the device's screen. Prevents a massive amount of work resisizing images over and over.

On my (relatively fast) phone it used to be very laggy to scroll with grid menus. It's fairly smooth after this change.

Release Note: Improved performance when scrolling on "grid" menu screens with large icons.

### CODE REVIEW

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@ctsims Build is failing

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@amstone326 fixed! Sorry about that, Weird issues with keeping master in sync and keeping jenkins, well, running.

**Comment by amstone326** [comment]
@ctsims Nevermind, I realized it was easy to fix myself so just did that and going to merge.

**Pull request merged**
