### PR TITLE
Backmerge 2.36.1

### PR DESCRIPTION
**Pull request by amstone326**
cross-request: https://github.com/dimagi/commcare-core/pull/582

### CODE REVIEW

**Comment by wpride** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by wpride** [comment]
@damagatchi retest this please

**Comment by wpride** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by wpride** [comment]
@damagatchi retest this please

**Comment by wpride** [comment]
@damagatchi retest this please

**Pull request merged**
