### PR TITLE
Protects wipeTable call with a tableExists check

### PR DESCRIPTION
**Pull request by shubham1g5**
Jira: Jira: https://dimagi-dev.atlassian.net/browse/REACH-102

Refer core PR for context. 

cross-request: https://github.com/dimagi/commcare-core/pull/843

### CODE REVIEW

**Comment by shubham1g5** [comment]
@ctsims  PRing for 2.45 again since it seems important for REACH.

**Comment by emord** [comment]
@shubham1g5 I don't think this is actually blocking REACH since there shouldn't be any users with 0 locations. I believe Nick just found this accidentally

**Comment by shubham1g5** [comment]
@emord thats great to know. Nick mentioned  in the Jira issue that's it's high prio so I was assuming it must be satisfying some use case for REACH.  If that's not the case, I would prefer it to not PR for 2.45.

**Comment by emord** [comment]
The fix I made for busting HQ's cache was high priority because it got around some issues around ICDS's consistent reversions. I don't htink this follow up is high enough priority to push into 2.45 if its at all risky/could be better tested

**Comment by shubham1g5** [comment]
@emord Thanks for the context. I am going to de-prio for 2.45.

**Pull request merged**
