### PR TITLE
GPS Maps: Focuses on last selected location

### PR DESCRIPTION
**Pull request by shubham1g5**
https://forum.dimagi.com/t/alternative-method-to-capture-gps-location/7373/1

### CODE REVIEW

**Comment by shubham1g5** [comment]
@ctsims That's right, which stops the marker to not shift to the current location.  if the user clicks on "my location" button subsequently the `manualSelectMode` gets discarded and the marker moves to the current location of the user.

**Comment by shubham1g5** [comment]
@ctsims  Yeah, I have added a functionality for changing the base layer, going to PR it in a bit.

**Comment by ctsims** [comment]
Amazing, thanks Shubham!

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Pull request merged**
