### PR TITLE
[SAAS-12293] Fix No Test Run error in BS

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
Sometimes when we retry the BS test, it gives an error `No Test Run` even though all the tests run successfully. 
This PR will fix it.

### CODE REVIEW

**Review by shubham1g5 — DISMISSED** [review]

**Comment by dimagimon** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:link: <a href="https://dimagi-dev.atlassian.net/browse/SAAS-12293">SAAS-12293</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by damagatchi** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462454/)

**Review by shubham1g5 — DISMISSED** [review]

**Comment by ShivamPokhriyal** [comment]
Rebased! @damagatchi retest this please

**Comment by damagatchi** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462463/)

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
