### PR TITLE
Remove form entry test sync temporarily

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**

### CODE REVIEW

**Comment by shubham1g5** [comment]
@ShivamPokhriyal  [Looks like](https://stackoverflow.com/a/11600182/3811963) you don't need to remove the complete test to deactivate it

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462048/)

**Comment by ShivamPokhriyal** [comment]
> @ShivamPokhriyal [Looks like](https://stackoverflow.com/a/11600182/3811963) you don't need to remove the complete test to deactivate it

Ohh nice. Will do the changes.

**Review by shubham1g5 — APPROVED** [review]

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462052/)

**Pull request merged**
