### PR TITLE
Update robo dependencies

### PR DESCRIPTION
**Pull request by wpride**
and remove deprecated setting

### CODE REVIEW

**Comment by amstone326** [comment]
@damagatchi retest this please

**Comment by wpride** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@wpride  Restoring the branch so that someone can potentially build on top of it.  Can you put a small comment describing at what stage this work is and what needs to be done next.

**Comment by wpride** [comment]
@shubham1g5 Sure! The tests are failing for this PR; the tricky part is they seem to be failing differently on Jenkins, Android Studio, and from the command line locally. The stack trace I see locally is:

```
java.lang.NullPointerException
	at com.android.internal.util.AsyncChannel.sendMessage(AsyncChannel.java:484)
	at com.android.internal.util.AsyncChannel.sendMessage(AsyncChannel.java:543)
	at android.net.nsd.NsdManager.discoverServices(NsdManager.java:562)
	at org.commcare.android.nsd.NSDDiscoveryTools.doDiscovery(NSDDiscoveryTools.java:108)
	at org.commcare.android.nsd.NSDDiscoveryTools.registerForNsdServices(NSDDiscoveryTools.java:56)
	at org.commcare.activities.UpdateActivity.onResume(UpdateActivity.java:138)
```

Which I've also not been able to track down - it seems possible we need to mock this NSD class for the tests.

**Pull request closed without merging**
