### PR TITLE
Remove unused cipher pool

### PR DESCRIPTION
**Pull request by shubham1g5**
## Summary

Removes unused cipher pool classes

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Safety story

Integration Tests should be enough testing on this.

### CODE REVIEW

**Comment by shubham1g5** [comment]
All tests passed except the `DateWidgetTests` which is unrelated, running the build without integration tests.
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by avazirna — APPROVED** [review]

**Comment by avazirna** [comment]
@shubham1g5 can we add some context about why we no longer need the cipher pool?

**Comment by shubham1g5** [comment]
> can we add some context about why we no longer need the cipher pool?

They are simply not used at the moment in the code.

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Pull request merged**
