### PR TITLE
Query Planner

### PR DESCRIPTION
**Pull request by ctsims**
Very simply query planner which give us a place to migrate optimizations we've been using for predicate evaluation and make informed decisions about which to use/not use when evaluating complex queries.

Also provides a Query Profiler which makes it possible to understand how a query was executed, and profile the runtime of that evaluation.
Note: Should re-center onto 2.33.1

cross-request: https://github.com/dimagi/commcare-core/pull/511

### CODE REVIEW

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
@damagatchi retest this please

**Comment by amstone326** [comment]
@ctsims I'm assuming by the don't pull label that this isn't ready for review yet, but let me know when it is and I'll try to get on it asap.

**Comment by ctsims** [comment]
@amstone326 As of last night we can start review on these two, but I'm hoping to do a cleanup/documentation pass on it.

**Comment by ctsims** [comment]
New PR https://github.com/dimagi/commcare-android/pull/1632

**Pull request closed without merging**
