### PR TITLE
[2.50.3] Deletes Raw Folder on Form Completion + Free Disk space Analytics

### PR DESCRIPTION
**Pull request by shubham1g5**
Long term port for [LTS PR](https://github.com/dimagi/commcare-android/pull/2385)

Product Note: CommCare no longer retains original images for a form in order to save disk storage used by CommCare. Smaller sized compressed copies are still retained and shown to the user in "Saved Forms" instead of the original images.

### CODE REVIEW

**Comment by shubham1g5** [comment]
Pr'ing this agains 2.50 to make sure this change makes in the 2.50.x LTS release.

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462082/)

**Review by ctsims — APPROVED** [review]
Looks good to me. A few files have the hanging newline issue, but I don't think that's a big deal in a historical / tagged release.

**Comment by shubham1g5** [comment]
@ctsims Think we need to add the one time task to clear the raw storage for already saved forms here as well as there will be LTS users who will directly be updating to this version (2.50.3) and would miss the larger one time cleanup that we rolled out in 2.48.11

**Comment by ctsims** [comment]
@shubham1g5 Ah, that's a good point and sounds worth integrating.

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462112/)

**Review by ctsims — APPROVED** [review]

**Pull request merged**
