### PR TITLE
App install Refactor

### PR DESCRIPTION
**Pull request by shubham1g5**
## Summary

Move app install handling to utils class for easy accessibility to Connect Classes. 

Best reviewed by commit

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

All our tests test for App installs 

### Safety story

minor refactor that seemingly is no-op with a good test coverage around refactored code.

### CODE REVIEW

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@damagatchi retest this please

**Review by avazirna — DISMISSED** [review]
@shubham1g5 this looks good to me, I just left a minor comment

**Review by OrangeAndGreen — DISMISSED** [review]

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by OrangeAndGreen — APPROVED** [review]

**Pull request merged**
