### PR TITLE
Default to current version while getting latestcommcareversion

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
A last minute fix for https://dimagi-dev.atlassian.net/browse/QA-1359

### CODE REVIEW

**Comment by shubham1g5** [comment]
@ShivamPokhriyal Wondering if we should also set this latest version info pref from the result obtained from the In app update APIs ?

**Comment by ShivamPokhriyal** [comment]
> @ShivamPokhriyal Wondering if we should also set this latest version info pref from the result obtained from the In app update APIs ?

Unfortunately using the [AppUpdateInfo](https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateInfo) we can only fetch the versionCode. So it's probably not possible to set the versionName using in-app-update apis.

**Comment by ShivamPokhriyal** [comment]
@shubham1g5 On second thought, Do you think it'd be a good idea to set the prefs from [here](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/tasks/ResourceEngineTask.java#L118)

**Comment by shubham1g5** [comment]
@ShivamPokhriyal I see . The required version is not always the latest version, an app can set that to whatever they want from app settings. So no other changes are required based on your comment.

**Pull request merged**
