### PR TITLE
Fixes Crash on App Resume after Session Expiration

### PR DESCRIPTION
**Pull request by shubham1g5**
## Summary

- Handles SessionExpiration in the home button view setup, this escapes the default session expiration and causes the app to crash when resuming after a session expiration event.  Other buttons already have this safety implemented and sync was the only one remaining. 

- Adds some helpful logs around session expiration

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### CODE REVIEW

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@shubham1g5 this looks right to me. I wonder if we should consider adding this to `2.54`

**Comment by shubham1g5** [comment]
>  I wonder if we should consider adding this to 2.54

Yeah that sounds good to me.

**Comment by shubham1g5** [comment]
Closing in favour of https://github.com/dimagi/commcare-android/pull/2814

**Pull request closed without merging**
