### PR TITLE
Removes default flags for RefreshToLatestBuildReceiver

### PR DESCRIPTION
**Pull request by shubham1g5**
It's really a no-op since both `enabled` and `exported` takes the removed values by default.

### CODE REVIEW

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Review by ctsims — APPROVED** [review]

**Review by ShivamPokhriyal — DISMISSED** [review]

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462013/)

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462014/)

**Comment by dimagimon** [comment]
[32% (0.0%) vs master 32%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462015/)

**Review by ShivamPokhriyal — APPROVED** [review]

**Pull request merged**
