### PR TITLE
Moves AndroidCaseInstanceTreeElement to core

### PR DESCRIPTION
**Pull request by shubham1g5**
## Summary

- No-op refactor to merge duplicate code between mobile and formplayer(https://github.com/dimagi/formplayer/pull/981)

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### Automated test coverage

There is test coverage around case db queries already. 

### Safety story

- Doesn't result in any effective code change, just moves the code to super class

cross-request: https://github.com/dimagi/commcare-core/pull/1008

### CODE REVIEW

**Comment by dimagimon** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR does not contain any JIRA issue keys in the PR title or commit messages (e.g. KEY-123)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damagatchi** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462511/)

**Comment by ctsims** [comment]
Hey @shubham1g5 

One thing - I think this set of PR's needs a bit of further de-risking.

It is true that there are unit tests for the area, and those tests do trigger the optimizations currently, but the tests don't technically ensure that the optimizations actually fire since they are quite deep in the code. They will catch an error where an optimization's code breaks the evaluation entirely, or produces the wrong result, but they won't catch an issue which results in an optimization no longer being applied. 

The easiest way to derisk, I think, would be to make sure the tests output a  [Reduced Trace Report, as in this example](https://github.com/dimagi/commcare-core/blob/d9066ea561f4ce85717b25263f9ddad695c98b29/src/main/java/org/commcare/cases/entity/NodeEntityFactory.java#L98) and manually inspect it to make sure the query plan didn't change before and after the tests. We could in theory hard code some aspect of the query plan into an actual testable condition  as well, which we've avoided in the past because it makes the tests dependent on the trace reporter, but might be worth revisiting now.

**Comment by shubham1g5** [comment]
@ctsims Added to tests in https://github.com/dimagi/commcare-core/pull/1006/commits/e13dd2da349e32efde3039ba5bd82e5b59ae287b to test for optimizations. I am simply testing for the the trace to include a stroage lookup text, not sure if that's what you were referring to as well or if there is a better way.

**Comment by shubham1g5** [comment]
checking if the test [here](https://github.com/dimagi/commcare-core/commit/e13dd2da349e32efde3039ba5bd82e5b59ae287b) looks good on this.

**Review by ctsims — APPROVED** [review]
Yup, I think that test should cover my concerns, thanks!

**Review by snopoke — APPROVED** [review]

**Pull request merged**
