### PR TITLE
Graph js fix

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
## Summary

2 commits for 2 issues 

- https://dimagi-dev.atlassian.net/browse/QA-3283?focusedCommentId=156140 In a bubble graph, when we click on a bubble, it expands, and on second click, it collapses to normal state. There is an issue with the update where on clicking the second time, instead of collapsing, the bubble disappears completely. 
The error for the same is: 
```
Error: <circle> attribute r: Expected length, "NaN".
(anonymous) @ d3.js:1211
selection_each @ d3.js:1176
selection_attr @ d3.js:1233
ChartInternal.unexpandCircles @ c3.max.js:9759
mouseout @ c3.max.js:8004
(anonymous) @ c3.max.js:8098
(anonymous) @ d3.js:1526
```
It happens because the `d.index` we expect here https://github.com/dimagi/commcare-android/blob/master/app/assets/graphing/graph.max.js#L75 is undefined. 
When we expand the `d` variable looks like this : `{x: 99718, value: 25000, id: "y0", index: 3}` i.e it has an index and it works. 
But when we collapse, the `d` variable becomes: `{id: "y0", id_org: "y0", values: Array(6)}` no index. 

I couldn't find much documentation around what exactly is `d` supposed to be. So I used this c3 configuration https://c3js.org/reference.html#point-focus-expand-enabled to disable the expansion of the bubbles at all. 

- https://dimagi-dev.atlassian.net/browse/QA-3285, the axis tick values were getting incorrectly formatted. This happened because we introduced a change due to which `tick` variable is always defined and has atleast one value `rotate` https://github.com/dimagi/commcare-core/blob/commcare_2.52/src/main/java/org/commcare/core/graph/c3/AxisConfiguration.java#L158, which was not true earlier. Earlier, the tick could be undefined. 
So I modified the check on graph.js to make sure that when the tick variable is defined, then atleast one of `values` or `count` is defined and then only apply the formatting. 

## Product Description

Removed support for expanding bubbles on click. 

## Safety Assurance

- [x] If the PR is high risk, "High Risk" label is set
- [x] I have confidence that this PR will not introduce a regression for the reasons below
- [x] Do we need to enhance manual QA test coverage ? If yes, "QA Note" label is set correctly

### CODE REVIEW

**Comment by dimagimon** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR does not contain any JIRA issue keys in the PR title or commit messages (e.g. KEY-123)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damagatchi** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462543/)

**Review by shubham1g5 — COMMENTED** [review]
> There is an issue with the update where on clicking the second time, instead of collapsing, the bubble disappears completely.

Is this also reproducible with the c3 preview online ? 

> So I used this c3 configuration https://c3js.org/reference.html#point-focus-expand-enabled to disable the expansion of the bubbles at all.

Is this a change from the behaviour today ? If so, would you be able to highlight it in product description section of PR.

**Comment by ShivamPokhriyal** [comment]
> Is this also reproducible with the c3 preview online ?

Yes it happens on the online preview as well. This is the javascript I used: 
```
var config = {
  data: {
    axes: {
      y0: "y"
    },
    colors: {
      y0: "#000000"
    },
    columns: [
      [
        "x0",
        98,
        12,
        61
      ],
      [
        "y0",
        25,
        23,
        22
      ]
    ],
    names: {
      y0: "adsfadsf"
    },
    type: "scatter",
    xs: {
      y0: "x0"
    },
    groups: [],
    labels: {},
    order: false
  },
  axis: {
    x: {
      show: true,
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0
      },
      label: {
        text: "Song ID",
        position: "outer-center"
      },
      tick: {
        rotate: 75
      }
    },
    y: {
      show: true,
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0
      },
      label: {
        text: "Number of words",
        position: "outer-middle"
      }
    },
    y2: {
      show: true,
      padding: {
        top: 0,
        right: 0,
        bottom: 0,
        left: 0
      },
      label: {
        text: "Nothing",
        position: "outer-middle"
      },
      tick: {
        values: []
      }
    }
  },
  interaction: {
    enabled: true
  },
  tooltip: {
    show: true,
    grouped: false
  },
};
config.point = {
    r: function(d) {
        return d.index * 30;
    },
    focus: {
        expand: {
          enabled: true
        }
    },
};
var chart = c3.generate(config);
```

> Is this a change from the behaviour today ? If so, would you be able to highlight it in product description section of PR.

Updated the description.

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
