### PR TITLE
Add login tests

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**
#2341

### CODE REVIEW

**Review by shubham1g5 — APPROVED** [review]

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by ShivamPokhriyal** [comment]
@damagatchi retest this please

**Comment by dimagimon** [comment]
[33% (0.0%) vs master 33%](https://jenkins.dimagi.com/job/commcare-android-pr-job-builder/462247/)

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
