### PR TITLE
Another Stream close

### PR DESCRIPTION
**Pull request by shubham1g5**

### CODE REVIEW

**Comment by ctsims** [comment]
Hey,

Are there specific issues prompting the second PR? I think that the best-practice for managing streams is always to close them in the same stack frame where they were created and to never close a stream that you were handed, so I'm a bit worried about closing streams in methods that don't have accountability for their lifecycle

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@damagatchi retest this please

**Comment by ctsims** [comment]
looks great, thanks!

**Pull request merged**
