### PR TITLE
Backmerge Commcare 2.54.0

### PR DESCRIPTION
**Pull request by avazirna**
## Summary
This PR back-merges changes from CommCare 2.54.0 into the master branch.

cross-request: https://github.com/dimagi/commcare-core/pull/1430

### CODE REVIEW

**Comment by avazirna** [comment]
@damagatchi retest this please

**Review by OrangeAndGreen — APPROVED** [review]

**Comment by avazirna** [comment]
@damagatchi retest this please

**Comment by avazirna** [comment]
@damagatchi retest this please

**Comment by shubham1g5** [comment]
@avazirna this needs to be duplicated to `formplayer` branch as well.

**Pull request merged**
